mantenedor/app/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from .views import Producto, Proveedor
from django.contrib.auth.views import LoginView,LogoutView

#---------- rutas de la API ----------------------------
urlpatterns = [
    path('api/', views.API_objects.as_view()),
    path('api/<int:pk>/', views.API_objects_details.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

#---------- rutas de la app ----------------------------
urlpatterns += [   
    path('', views.index),
    path('quienes', views.quienes),
    path('nba', views.nba),
    path('finalFantasy', views.finalFantasy),
    path('blairWitch', views.blairWitch),
    path('ingresarProducto', views.ingresarProducto),
    path('ingresarProveedor', views.ingresarProveedor),
    path('listarProductosFull', views.listarProductosFull),
    path('listarProveedoresFull', views.listarProveedoresFull),
    path('editarProducto/<int:producto_id>', views.editarProducto),
    path('editarProveedor/<int:proveedor_id>', views.editarProveedor),
    path('borrarProducto/<int:producto_id>', views.borrarProducto),
    path('borrarProveedor/<int:proveedor_id>', views.borrarProveedor),
    path('listarProductos', views.listarProductos),
     path('listarProveedores', views.listarProveedores),
    path('inicio', views.inicio),
    
]

#---------- login ----------------------------
urlpatterns+= [
     
    #path('',views.indexView,name='home'),
    #path('dashboard/',views.dashboardView,name='dashboard'),
    path('login/',LoginView.as_view(),name='login_url'),
    path('register/',views.registerView,name='register_url'),
    path('logout/',LogoutView.as_view(),name='logout_url'),
]

mantenedor/appCrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('ingresarProducto', include('app.urls')),
    path('ingresarProveedor', include('app.urls')),
    path('listarProductosFull', include('app.urls')),
    path('listarProveedoresFull', include('app.urls')),
    path('editarProducto/<int:producto_id>', include('app.urls')),
    path('editarProveedor/<int:proveedor_id>', include('app.urls')),
    path('borrarProducto/<int:producto_id>', include('app.urls')),
    path('borrarProveedor/<int:proveedor_id>', include('app.urls')),
    path('listarProductos', include('app.urls')),
    path('listarProveedores', include('app.urls')),
]

mantenedor/app/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _


# Create your models here.


class Proveedor(models.Model):

    rut = models.CharField(max_length=15)
    nombre = models.CharField(max_length=50)
    telefono = models.CharField(max_length=20)
    domicilio = models.CharField(max_length=50)
    region = models.CharField(max_length=50, blank=True, null=True)
    comuna = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    proveedor = models.ForeignKey(Proveedor, null=True, blank=True, on_delete=models.CASCADE)
    codigo = models.IntegerField()
    sku = models.IntegerField()
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=30)
    clasificacion = models.CharField(max_length=30)
    precio = models.IntegerField()
    disponible = models.IntegerField()

    def __str__(self):
        return self.nombre

mantenedor/app/templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">


<head>
    <title>{% block title %} AdministradorCompras {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/estiloMenu.css' %}" rel="stylesheet">
    <link href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/estiloFormLogin.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->



</head>
<style>
    body {
    background-image: url( "{% static 'img/supermercado.png' %}");
    background-position: center;
    background-repeat: no-repeat;
    background-size: 100% 100%;
    background-attachment: fixed;
  }
  span{
    color: rgba(0,0,0,0);
  }
</style>
<dir class="titulo">
    Supermercado La Bodeguita <img src="{% static 'img/carrito.png' %}" alt=""> 
    {% if user.is_authenticated %} <span>123456789101112131415</span>Bienvenido {{user.username}}
    {% else %}<span>123456789101112131415</span>Bienvenido Proveedores{% endif %}
</dir>
<span>12345678910</span>

<body>
   
    
    <header class="titulo3">
        
        <input type="checkbox" id="btn-menu">
        <label for="btn-menu"><img src="{% static 'img/imgMenu/menu.png' %}" alt="">
        </label>
        <nav class="menu">
            <ul>
                
                {% if user.is_authenticated %}

                <li><a href="http://localhost:8000/listarProductos"><span class="icon-file-text"></span> Listar
                        Productos</a></li>

                <li><a href="http://localhost:8000/listarProveedores"><span class="icon-file-text"></span> Listar
                        Proveedores</a></li>

                <li><a href="http://localhost:8000/listarProductosFull"><span class="icon-file-text"></span> Editar
                        Producto</a></li>
                <li><a href="http://localhost:8000/listarProveedoresFull"><span class="icon-file-text"></span> Editar
                        Proveedor</a></li>

                <li><a href="http://localhost:8000/ingresarProducto"><span class="icon-file-text"></span> Agregar
                        Producto</a></li>
                <li><a href="http://localhost:8000/ingresarProveedor"><span class="icon-file-text"></span> Agregar
                        Proveedor</a></li>
                <li><a href="http://localhost:8000/logout/"><span class="icon-clipboard"></span> Cerrar Sesión</a>
                </li>



                {% else %}
                <li><a href="http://localhost:8000/"><span class="icon-home"></span> Inicio</a></li>
                <li><a href="http://localhost:8000/quienes"><span class="icon-rocket"></span> Nosotros</a></li>
                <li><a href="https://twitter.com"><span class="icon-twitter-square"></span> Twitter</a></li>
                <li><a href="https://facebook.com"><span class="icon-facebook-square"></span> Facebook</a></li>
                <li><a href="https://web.whatsapp.com/"><span class="icon-whatsapp"></span> Whatsapp</a></li>
                <li><a href="https://gmail.com"><span class="icon-envelop"></span> Correo</a></li>
                <li><a href="http://localhost:8000/inicio"><span class="icon-clipboard"></span> Iniciar Sesión</a>
                </li>

                {% endif %}
            </ul>

        </nav>


    </header>

   
</body>
{% block content %}
{% endblock %}

{% block footer %}

{% endblock %}


<!-- Scripts -->

<!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->

<script src="{% static 'js/jquery-latest.js' %}"></script>
<script src="{% static 'js/menu.js' %}"></script>
<script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-latest.js' %}"></script>
<!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->








</html>

mantenedor/app/templates/app/baseAgregar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">


<head>
    <title>{% block title %} AdministradorCompras {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/estiloMenu.css' %}" rel="stylesheet">
    <link href="{% static 'css/estiloSubMenu.css' %}" rel="stylesheet">
    <link href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">



</head>

<body>
    <header>
        <input type="checkbox" id="btn-menu">
        <label for="btn-menu"><img src="{% static 'img/imgMenu/menu.png' %}" alt="">
        </label>
        <nav class="menu">
            <ul>
                
                {% if user.is_authenticated %}

                <li><a href="http://localhost:8000/listarProductos"><span class="icon-file-text"></span> Listar
                        Productos</a></li>

                <li><a href="http://localhost:8000/listarProveedores"><span class="icon-file-text"></span> Listar
                        Proveedores</a></li>

                <li><a href="http://localhost:8000/listarProductosFull"><span class="icon-file-text"></span> Editar
                        Producto</a></li>
                <li><a href="http://localhost:8000/listarProveedoresFull"><span class="icon-file-text"></span> Editar
                        Proveedor</a></li>

                <li><a href="http://localhost:8000/ingresarProducto"><span class="icon-file-text"></span> Agregar
                        Producto</a></li>
                <li><a href="http://localhost:8000/ingresarProveedor"><span class="icon-file-text"></span> Agregar
                        Proveedor</a></li>
                <li><a href="http://localhost:8000/logout/"><span class="icon-clipboard"></span> Cerrar Sesión</a>
                </li>



                {% else %}
                <li><a href="http://localhost:8000/"><span class="icon-home"></span> Inicio</a></li>
                <li><a href="http://localhost:8000/quienes"><span class="icon-rocket"></span> Nosotros</a></li>
                <li><a href="https://twitter.com"><span class="icon-twitter-square"></span> Twitter</a></li>
                <li><a href="https://facebook.com"><span class="icon-facebook-square"></span> Facebook</a></li>
                <li><a href="https://web.whatsapp.com/"><span class="icon-whatsapp"></span> Whatsapp</a></li>
                <li><a href="https://gmail.com"><span class="icon-envelop"></span> Correo</a></li>
                <li><a href="http://localhost:8000/inicio"><span class="icon-clipboard"></span> Iniciar Sesión</a>
                </li>

                {% endif %}
            </ul>

        </nav>


    </header>

   
</body>
{% block content %}
{% endblock %}

{% block footer %}

{% endblock %}


<!-- Scripts -->

<!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->









</html>

mantenedor/app/templates/app/baseInicio.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">


<head>
    <title>{% block title %} AdministradorCompras {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/estiloMenu.css' %}" rel="stylesheet">
    <link href="{% static 'css/estiloSubMenu.css' %}" rel="stylesheet">
    <link href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">



</head>

<body>
    <header>
        <input type="checkbox" id="btn-menu">
        <label for="btn-menu"><img src="{% static 'img/imgMenu/menu.png' %}" alt="">
        </label>
        <nav class="menu">
            <ul>
                <li><a href="http://localhost:8000/"><span class="icon-home"></span> Inicio</a></li>
                <li><a href="http://localhost:8000/quienes"><span class="icon-rocket"></span> Nosotros</a></li>
                <li><a href="https://twitter.com"><span class="icon-twitter-square"></span> Twitter</a></li>
                <li><a href="https://facebook.com"><span class="icon-facebook-square"></span> Facebook</a></li>
                <li><a href="https://web.whatsapp.com/"><span class="icon-whatsapp"></span> Whatsapp</a></li>
                <li><a href="https://gmail.com"><span class="icon-envelop"></span> Correo</a></li>
                <li><a href="http://localhost:8000/inicio"><span class="icon-clipboard"></span> Iniciar Sesión</a>
                </li>
            </ul>

        </nav>


    </header>

    <aside>
        <input type="checkbox" id="btn-menu2">
        <label for="btn-menu2"><img src="{% static 'img/imgMenu/menu.png' %}" alt="">
        </label>
        <nav class="menu2">
            <ul>



                {% if user.is_authenticated %}

                <li><a href="http://localhost:8000/listarProductos"><span class="icon-file-text"></span> Listar
                        Productos</a></li>

                <li><a href="http://localhost:8000/listarProveedores"><span class="icon-file-text"></span> Listar
                        Proveedores</a></li>

                <li><a href="http://localhost:8000/listarProductosFull"><span class="icon-file-text"></span> Editar
                        Producto</a></li>
                <li><a href="http://localhost:8000/listarProveedoresFull"><span class="icon-file-text"></span> Editar
                        Proveedor</a></li>

                <li><a href="http://localhost:8000/ingresarProducto"><span class="icon-file-text"></span> Agregar
                        Producto</a></li>
                <li><a href="http://localhost:8000/ingresarProveedor"><span class="icon-file-text"></span> Agregar
                        Proveedor</a></li>
                <li><a href="http://localhost:8000/logout/"><span class="icon-clipboard"></span> Cerrar Sesión</a>
                </li>



                {% else %}
                <li><a href="http://localhost:8000/inicio"><span class="icon-clipboard"></span> Iniciar Sesión</a>
                </li>

                {% endif %}
            </ul>
        </nav>
    </aside>
</body>
{% block content %}
{% endblock %}

{% block footer %}

{% endblock %}


<!-- Scripts -->

<!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->

<script src="{% static 'js/jquery-latest.js' %}"></script>
<script src="{% static 'js/menu.js' %}"></script>
<script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-latest.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>








</html>

mantenedor/app/templates/app/baseLogin.html
{% load staticfiles %}
<!DOCTYPE html>
<html >

        
<head>
    <title>Gamers{% block title %} Title {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script> -->



    
</head>

<style>
    body {
    background-image: url( "{% static 'img/fondo.png' %}");
    background-position: center;
    background-repeat: no-repeat;
    background-size: 100% 100%;
    background-attachment: fixed;
  }
</style>
 
<body >

   

    {% block content %}   
    {% endblock %}

    {% block footer %}
    <!-- Pie de página -->
    <div id="footer">
        
    </div>
    {% endblock %}    

mantenedor/app/templates/app/editarProducto.html
{% extends 'app/base.html' %}

{% block content %}


<body>
    <h1 class="f">Editar Producto</h1>
   <form class="g" method="POST">
        {{ form }}
        {% csrf_token %}
        <button  type="submit" >Editar</button><button><a href="http://localhost:8000/listarProductosFull">Volver</a></button>
   </form>
</body>
{% endblock content %}

mantenedor/app/templates/app/editarProveedor.html
{% extends 'app/base.html' %}

{% block content %}
{% load staticfiles %}



<body>
    <h1 class="f">Editar Proveedor</h1>
   <form class="g" method="POST">
        {{ form }}
        {% csrf_token %}
        <button  type="submit" >Editar</button><button><a href="http://localhost:8000/listarProveedoresFull">Volver</a></button>
   </form>
</body>
{% endblock content %}

mantenedor/app/templates/app/ingresarProducto.html
{% extends 'app/base.html' %}

{% block content %}
{% load staticfiles %}
<link href="{% static 'css/botonLogin.css' %}" rel="stylesheet">




<body>
    <h1 class="centrar" class="f">Ingresar Producto</h1>

    <div id="registro" class="container">

        <style>
            .centrar{
                text-align: left; 
                background:#185468;
                
               
               
                margin-left: 15%;
                width: 55%;
                color:  rgb(210, 217, 248);
                font-size: 35px;
               
            }
            .centrar2{
                text-align: left; 
                background: royalblue;
                margin-left: 20%;
                width: 50%;
                color: rgb(210, 217, 248);
                font-size: 35px;
            }
            .tam{
                font-size: 20px;
            }
        </style>

        <form class="centrar" role="form" enctype="multipart/form-data" action="" method="POST" id="upload-image-form"
            id="formularioProveedor">


            <!-- {% csrf_token %} -->
            <div class="centrar"class="form-group">

                <label for="id_nombre">Nombre Empresa:</label>
                {% csrf_token %}
                {{ formProducto.proveedor}}

            </div>

            <!-- {{ form}} -->
            <div class="centrar" class="form-group">
                <label for="id_codigo">Codigo:</label><input class="tam" type="number" name="codigo" maxlength="13" required=""
                    id="id_codigo" class="form-control" placeholder="Ingrese Código EAN">
            </div>
            <div class="centrar" class="form-group">
                <label for="id_sku">Sku:</label><input class="tam" type="number" name="sku" maxlength="6" required="" id="id_sku"
                    class="form-control" placeholder="Ingrese Código Interno">
            </div>
            <div class="centrar" class="form-group">
                <label for="id_nombre">Nombre:</label><input class="tam" type="text" name="nombre" maxlength="50" required=""
                    id="id_nombre" class="form-control" placeholder="Ingrese Nombre Producto">
            </div>
            <div class="centrar" class="form-group">
                <label for="id_descripcion">Descripción:</label><input class="tam" type="text" name="descripcion" maxlength="50"
                    required="" id="id_descripcion" class="form-control" placeholder="Ingrese Descripción">
            </div>
            <div class="centrar" class="form-group">
                <label for="id_clasificasion">Clasificación:</label><input class="tam" type="text" name="clasificacion"
                    maxlength="50" required="" id="id_clasificasion" class="form-control" placeholder="Ingrese Nombre">
            </div>
            <div class="centrar" class="form-group">
                <label for="id_precio">Precio:</label><input class="tam" type="number" name="precio" maxlength="50" required=""
                    id="id_precio" class="form-control" placeholder="Ingrese Precio">
            </div>
            <div class="centrar" class="form-group">
                <label for="id_disponible">Disponible:</label><input class="tam"type="number" name="disponible" maxlength="8"
                    required="" id="id_disponible" class="form-control" placeholder="Ingrese Unidades">
            </div>


            <button class="button" type="submit">GRABAR</button>
        </form>
    </div>
    <script src="{% static 'js/validadorform.js' %}"></script>
</body>
{% endblock content %}

mantenedor/app/templates/app/listarProductos.html
{% extends 'app/base.html' %}

{% block content %}
{% load staticfiles %}
<link href="{% static 'css/estilosTabla.css' %}" rel="stylesheet">

<body>

    <div>
        <form class="centra" class="flot" action="/listarProductos" method="POST">

            <div>
                <div>
                    <div>
                        <h1>Buscar por Precio:</h1>
                    </div >

                    <input type="number" name="precio" value="{{precio}}" style="width:100px" />
                    
                        <input  class="button" type="submit" value="Buscar">
                    
                    
                </div>

                <div>
                    <div>
                        <h1>Buscar por Clasificación:</h1>
                    </div>

                    <input type="text" name="clasificacion" value="{{clasificacion}}" style="width:100px" />
                    <input class="button" type="submit" value="Buscar">
                </div>

            </div>
            <br>
            <br>




            {% csrf_token %}
            <input class="button" action="/listarProductos" type="submit" value="Mostrar Todos">
        </form>
    </div>







   
   



    {% for c in producto %}

    

    <body>
        



        <div id="tabla" id="divt">
            <div class="A" id="divt"><strong>Proveedor:  </strong>{{c.proveedor}}</div>
            <div class="B" id="divt"><strong>Código:  </strong>{{c.codigo}}</div>
            <div class="C" id="divt"><strong>SKU:  </strong>{{c.sku}}</div>
            <div class="D" id="divt"><strong>Nombre:  </strong>{{c.nombre}}</div>
            <div class="E" id="divt"><strong>Descripción:  </strong>{{c.descripcion}}</div>
            <div class="F" id="divt"><strong>Clasificación:  </strong>{{c.clasificacion}}</div>
            <div class="G" id="divt"><strong>Precio:  </strong>{{c.precio}}</div>
            <div class="H" id="divt"><strong>Disponible:  </strong>{{c.disponible}}</div>
        </div>




       
    </body>

    </form>


    {% endfor%}

</body>
{% endblock content %}

mantenedor/app/templates/app/listarProductosFull.html
{% extends 'app/base.html' %}

{% block content %}

{% load staticfiles %}


<h3 class="user">Bienvenido </h3>
<h3 class="user">{{user.username}}</h3>
<h1 class="f">Editar Productos </h1>
<body>
        <form class="flot" action="/listarProductosFull" method="POST">
            <div >
                <div>
                       <h1>Buscar por Precio:</h1> 
                </div>
                   
                    <input  type="number" name="precio" value="{{precio}}" style="width:100px" / >
                    <input   type="submit" value="Buscar">
            </div >

            <div >
                    <div>
                            <h1>Buscar por Clasificación:</h1> 
                     </div>
                    
                    <input  type="text" name="clasificacion" value="{{clasificacion}}" style="width:100px" / >
                    <input  type="submit" value="Buscar">
            </div>
            <br>
            <br>
           
           
            
            {% csrf_token %}
            <input  action="/listarProductos" type="submit" value="Mostrar Todos">
        </form>
    
        
            {% for c in producto %}
            
                <form  role="form" enctype="multipart/form-data" action="" method="POST" id="upload-image-form">
                    <div class="btit" id="tcen" >
                        <div > PROVEEDOR </div><div  class="czise">{{c.proveedor}}</div>
                        <div > CODIGO </div><div  class="czise">{{c.codigo}}</div>
                        <div > SKU </div><div  class="czise">{{c.sku}}</div>
                        <div > NOMBRE </div><div  class="czise">{{c.nombre}}</div>
                        <div > DESCRIPCION </div><div  class="czise">{{c.descripcion}}</div>          
                        <div > CLASIFICACIÓN </div><div  class="czise">{{c.clasificacion}}</div>
                        <div > PRECIO </div><div  class="czise">$ {{c.precio}}</div>
                        <div > DISPONIBLE </div><div  class="czise">$ {{c.disponible}}</div>
                        <div >
                            <a href="/editarProducto/{{c.id}}"> EDITAR</a>
                            <a class="rb"href="/borrarProducto/{{c.id}}" onclick="return confirm('¿Seguro de borrar?');"> BORRAR</a>
                        </div>
                    </div>
                    
                </form>
            
            {% endfor%}

            
            
    
</body>




{% endblock content %}

mantenedor/app/templates/app/listarProveedores.html
{% extends 'app/base.html' %}

{% block content %}
{% load staticfiles %}
<link href="{% static 'css/estilosTabla.css' %}" rel="stylesheet">

<body>
    <div>
        <form class="centra" class="flot" action="/listarProveedores" method="POST">

            <div>
                <div>
                    <div>
                        <h1>Buscar por Nombre:</h1>
                    </div >

                    <input type="number" name="precio" value="{{nombre}}" style="width:100px" />
                    
                        <input  class="button" type="submit" value="Buscar">
                    
                    
                </div>

                <div>
                    <div>
                        <h1>Buscar por Rut:</h1>
                    </div>

                    <input type="text" name="clasificacion" value="{{rut}}" style="width:100px" />
                    <input class="button" type="submit" value="Buscar">
                </div>

            </div>
            <br>
            <br>




            {% csrf_token %}
            <input class="button" action="/listarProveedores" type="submit" value="Mostrar Todos">
        </form>
    </div>





    {% for c in proveedor %}

    

    <body>
        



        <div id="tabla" id="divt">
            <div class="A" id="divt"><strong>RUT:  </strong>{{c.rut}}</div>
            <div class="B" id="divt"><strong>Nombre:  </strong>{{c.nombre}}</div>
            <div class="C" id="divt"><strong>Télefono:  </strong>{{c.telefono}}</div>
            <div class="D" id="divt"><strong>Domicilio:  </strong>{{c.domicilio}}</div>
            <div class="E" id="divt"><strong>Región:  </strong>{{c.region}}</div>
            <div class="F" id="divt"><strong>Comuna:  </strong>{{c.comuna}}</div>
            
        </div>

        
        
    </body>

    </form>


    {% endfor%}

</body>
{% endblock content %}

mantenedor/app/templates/app/listarProveedoresFull.html
{% extends 'app/base.html' %}

{% block content %}

{% load staticfiles %}


<h3 class="user">Bienvenido </h3>
<h3 class="user">{{user.username}}</h3>
<h1 class="f">Editar Proveedores </h1>

<body>

    {% csrf_token %}
    <input  action="/listarProveedores" type="submit" value="Mostrar Todos">
</form>
    
    {% for c in proveedor %}
    <form role="form" enctype="multipart/form-data" action="" method="POST" id="upload-image-form">
        <div class="btit" id="tcen">




            <div> RUN </div>
            <div class="czise">{{c.rut}}</div>
            <div> NOMBRE </div>
            <div class="czise">{{c.nombre}}</div>
            <div> APELLIDO PATERNO </div>
            <div class="czise"> {{c.apellido_paterno}}</div>
            <div> APELLIDO MATERNO </div>
            <div class="czise">{{c.apellido_materno}}</div>
            <div> TELÉFONO </div>
            <div class="czise"> {{c.telefono}}</div>
            <div> DOMICILIO </div>
            <div class="czise"> {{c.domicilio}}</div>
            <div> REGIÓN </div>
            <div class="czise"> {{c.region}}</div>
            <div> COMUNA </div>
            <div class="czise"> {{c.comuna}}</div>
            <div> FECHA NACIMIENTO </div>
            <div class="czise"> {{c.fecha_nacimiento}}</div>
            <div> PRODUCTO </div>
            <div class="czise">{{c.producto}}</div>
            <a href="/editarProveedor/{{c.id}}"> EDITAR</a>
            <a class="rb" href="/borrarProveedor/{{c.id}}" onclick="return confirm('¿Seguro de borrar?');">
                BORRAR</a>
        </div>



        </div>

    </form>



    {% endfor%}



</body>




{% endblock content %}

mantenedor/app/templates/app/proveedor_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>primera pagina DJango</title>
</head>
<body>
    <h1>LLegamos a la plantilla</h1>
</body>
</html>